### PR TITLE
fix: Sync design for search location modal

### LINKED ISSUE #670: [Designsync] Update search input pattern
- Use same styling as other inputs
- Update buttons (see issue #667 )

Figma / Components 1.0 / Inputs https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=335%3A662
Figma / App 1.0 / Action / Search https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=1%3A4

image

### LINKED ISSUE #671: [Designsync] Update search result list
- Update subheading
- Use subheading for all list-types

Figma / Components 1.0 / List-groups https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=547%3A5502
Figma / App 1.0 / Action / Search https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=1%3A4

image
image

### LINKED ISSUE #719: [Designsync] Update Map selection to design in Figma
image

### PR DESCRIPTION
**Pull request by mikaelbr**
- Fixes #670 
- Fixes #671
- Fixes #719 

Note: I've not yet redefined the window flow here. It is still a modal. I think we should talk about the navigation flow at some point.

Examples:

Screenshot 2020-11-24 at 13 58 56
Screenshot 2020-11-24 at 13 58 48

### CODE REVIEW

File: src/location-search/LocationSearch.tsx [hunk 1]
```diff
@@ -178,52 +178,53 @@ const LocationSearch: React.FC<Props> = ({
...
-            <MessageBox
-              type="warning"
-              message={errorMessage}
-              containerStyle={{marginBottom: 12}}
+      {error && (
+        <View style={styles.contentBlock}>
+          <MessageBox
+            type="warning"
+            message={errorMessage}
+            containerStyle={{marginBottom: 12}}
```
Comment (rikkekantega) [inline src/location-search/LocationSearch.tsx:188]: This little guy has managed to escape every theming effort so far... Wonder if it will survive this time. :thinking:

Comment (mikaelbr) [reply src/location-search/LocationSearch.tsx:188]: Hirr 😄  I'll fix it. The added indentation (due to wrapped element) will cause this to show my name in git blame 🚀

File: src/location-search/map-selection/index.tsx [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import {RouteProp} from '@react-navigation/native';
 import React, {useState, useRef, useMemo} from 'react';
-import {View, TouchableOpacity} from 'react-native';
+import {View, TouchableOpacity, Text} from 'react-native';
```
Comment (rikkekantega) [inline src/location-search/map-selection/index.tsx:3]: Unused Text?

File: src/components/map/PositionArrow.tsx [hunk 3]
```diff
@@ -1,34 +1,29 @@
...
+      mode="primary"
       accessibilityLabel="Min posisjon"
       accessibilityRole="button"
       onPress={flyToCurrentLocation}
-    >
-      <View style={styles.flyToButton}>
-        <ThemeIcon svg={CurrentLocationArrow} />
-      </View>
-    </TouchableOpacity>
+      hitSlop={insets.symmetric(12, 20)}
```
Comment (rikkekantega) [inline src/components/map/PositionArrow.tsx:19]: Wonder if we could make hitslops all over a themed value instead (just thinking out loud, not suggesting that you need to implement it here)

File: src/location-search/map-selection/index.tsx (hunk 2 above)
Comment (mikaelbr) [reply src/location-search/map-selection/index.tsx]: Great catch

File: src/components/map/PositionArrow.tsx (hunk 3 above)
Comment (mikaelbr) [reply src/components/map/PositionArrow.tsx:19]: Yeah, worth a discussion. If there are any drawpacks. There can be cases where buttons are closely aligned for instance.

File: src/location-search/LocationSearch.tsx (hunk 1 above)
Comment (mikaelbr) [reply src/location-search/LocationSearch.tsx]: Fixed

**Review by rikkekantega — APPROVED** [review]
LGTM :rocket: :ship:
