### PR TITLE
fix: TB announces previous results on empty field

### LINKED ISSUE #1349: [BUG] [UU] SR leser opp forrige valgte ankomstested når feltet er blankt
### Observasjon
Ved reisesøk på startskjermen, hvis man f.eks klikker en favoritt slik at det blir satt som ankomststed og gjennmfører et søk, for deretter å klikke reset (logo øverst til venstre) oppstår denne buggen.
Nå er skjemaet resatt, og feltet for ankomstested er tomt. Men hvis man setter fokus på dette feltet med skjermleser, leses det opp at ankomststed er satt til det du brukte sist.

### Analyse
accessibiliy label blir ikke resatt skikkelig når location er undefined.

### Implementasjon
accessibilitylabel settes til tom streng når location er undefined

### Testbeskrivelse
se Observasjon

### PR DESCRIPTION
**Pull request by monopoint**
resolves #1349

### CODE REVIEW

**Review by cbrevik — APPROVED** [review]

File: src/components/sections/location-input.tsx [hunk 1]
```diff
@@ -33,6 +33,8 @@ export default function LocationInput({
         t(SectionTexts.locationInput.a11yValue(currentValueLabel)) +
         screenReaderPause,
     };
+  } else {
+    props.accessibilityValue = {text: ''}; // this must be reset or TB will announce previous result
```
Comment (cbrevik) [inline src/components/sections/location-input.tsx:37]: test
